databases:
  - name: shopz
    databaseName: shopz
    user: shopz

services:
  - type: web
    name: shopz
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shopz
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
